<#
  changelog.ps1 - build the GitHub release body for RFERP.

  Combines, in order:
    1. hand-written bilingual highlights (release-notes.txt)
    2. the PR list GitHub generates from .github/release.yml (grouped by label)
    3. commits pushed straight to main that belong to no merged PR

  Commits whose subject contains [skip changelog] are left out.

  Usage:
    powershell -NoProfile -ExecutionPolicy Bypass -File changelog.ps1 -Version 1.2.0
#>
param(
  [Parameter(Mandatory = $true)][string]$Version,
  [string]$PrevTag,
  [string]$Repo,
  [string]$Highlights = "release-notes.txt",
  [string]$Out = "release-notes.full.md",
  [string]$TargetBranch = "main"
)

$ErrorActionPreference = "Stop"

# gh emits UTF-8 (emoji, Chinese); decode child output as UTF-8 instead of the
# console code page, otherwise the release body comes out mangled.
[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false)
$OutputEncoding = New-Object System.Text.UTF8Encoding($false)

$tag = if ($Version.StartsWith("v")) { $Version } else { "v$Version" }

if (-not $Repo) {
  $url = (& git remote get-url origin 2>$null | Out-String).Trim()
  if ($url -match "github\.com[:/]([^/]+/[^/\.]+)") { $Repo = $Matches[1] }
}
if (-not $Repo) { throw "cannot determine the repository; pass -Repo owner/name" }

if (-not $PrevTag) {
  $PrevTag = (& git describe --tags --abbrev=0 --match "v*" 2>$null | Out-String).Trim()
}
# if this release's tag already exists locally, step back one release
if ($PrevTag -eq $tag) {
  $PrevTag = (& git describe --tags --abbrev=0 --match "v*" "$tag^" 2>$null | Out-String).Trim()
}
if (-not $PrevTag) { Write-Warning "no previous tag found; the PR list will be omitted" }

$lines = New-Object System.Collections.Generic.List[string]

# 1) hand-written bilingual highlights
if ($Highlights -and (Test-Path -LiteralPath $Highlights)) {
  $h = (Get-Content -LiteralPath $Highlights -Raw -Encoding UTF8).TrimEnd()
  if ($h) {
    foreach ($l in ($h -split "`r?`n")) { $lines.Add($l) }
    $lines.Add("")
    $lines.Add("---")
    $lines.Add("")
  }
}

# 2) PR list generated by GitHub from .github/release.yml
$auto = ""
if ($PrevTag) {
  $gh = if ($env:GH) { $env:GH } else { "gh" }
  $ghArgs = @(
    "api", "-X", "POST", "repos/$Repo/releases/generate-notes",
    "-f", "tag_name=$tag",
    "-f", "target_commitish=$TargetBranch",
    "-f", "previous_tag_name=$PrevTag"
  )
  try {
    $json = (& $gh @ghArgs 2>$null | Out-String)
    $auto = ($json | ConvertFrom-Json).body
  } catch {
    Write-Warning "could not fetch the generated PR list: $($_.Exception.Message)"
  }
}

$link = ""
if ($auto) {
  $m = [regex]::Match($auto, "(?m)^\*\*Full Changelog\*\*:.*$")
  if ($m.Success) {
    $link = $m.Value
    $auto = $auto.Remove($m.Index, $m.Length).TrimEnd()
  }
  foreach ($l in ($auto -split "`r?`n")) { $lines.Add($l) }
  $lines.Add("")
}

# 3) commits pushed straight to main (mainline, non-merge)
if ($PrevTag) {
  $range = "$PrevTag..HEAD"
  $direct = @(& git log --first-parent --no-merges --format="%h %s" $range 2>$null |
    Where-Object { $_ -and ($_ -notmatch "\[skip changelog\]") })
  if ($direct.Count -gt 0) {
    $lines.Add("### Direct commits / 直接提交")
    $lines.Add("")
    foreach ($c in $direct) { $lines.Add("* $c") }
    $lines.Add("")
  }
}

if ($link) { $lines.Add($link) }

$text = ($lines -join "`n").TrimEnd() + "`n"
[System.IO.File]::WriteAllText([System.IO.Path]::GetFullPath($Out), $text, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "wrote $Out ($($direct.Count) direct commit(s), PR list: $(if ($auto) { 'yes' } else { 'no' }))"
